<script setup lang="ts">
import { computed } from 'vue'
import {
  Bath,
  Bed,
  BedDouble,
  Beer,
  Bike,
  Bird,
  BookOpen,
  BrickWall,
  Building,
  Building2,
  Cake,
  CakeSlice,
  Calculator,
  Camera,
  Car,
  Cat,
  ChefHat,
  ChessPawn,
  Circle,
  CircleDot,
  Clapperboard,
  Clock,
  Cloud,
  Club,
  Coffee,
  Computer,
  CookingPot,
  Cpu,
  Croissant,
  CupSoda,
  Dices,
  DoorOpen,
  Dumbbell,
  Ear,
  Fence,
  FilePlay,
  FileText,
  Film,
  Fish,
  Flame,
  Flower,
  Flower2,
  Footprints,
  Frame,
  Gamepad,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  GlassWater,
  GraduationCap,
  Hammer,
  Hand,
  Handbag,
  Headphones,
  Heart,
  Home,
  HousePlus,
  IceCream,
  Landmark,
  Languages,
  Map,
  MapPinned,
  MessageCircle,
  MessageCircleMore,
  Mic,
  Mic2,
  Mountain,
  Music,
  Origami,
  Palette,
  PartyPopper,
  Pencil,
  PersonStanding,
  Plane,
  Puzzle,
  Salad,
  Sandwich,
  Scissors,
  ShelvingUnit,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Smartphone,
  Snowflake,
  Soup,
  Sparkles,
  Star,
  Store,
  Sun,
  Swords,
  Table,
  Target,
  Tent,
  Ticket,
  TrafficCone,
  Train,
  TreePine,
  Trophy,
  Tv,
  Type,
  University,
  UserRound,
  Users,
  Utensils,
  Waves,
  WandSparkles,
  Wine,
  Zap
} from 'lucide-vue-next'

interface Props {
  iconName: string
  size?: number
  customClass?: string
}

const props = withDefaults(defineProps<Props>(), {
  size: 24,
  customClass: ''
})

// Map kebab-case icon names to PascalCase components
const iconMap: Record<string, typeof Sparkles> = {
  'bath': Bath,
  'bed': Bed,
  'bed-double': BedDouble,
  'beer': Beer,
  'bike': Bike,
  'bird': Bird,
  'book-open': BookOpen,
  'brick-wall': BrickWall,
  'building': Building,
  'building-2': Building2,
  'cake': Cake,
  'cake-slice': CakeSlice,
  'calculator': Calculator,
  'camera': Camera,
  'car': Car,
  'cat': Cat,
  'chef-hat': ChefHat,
  'chess-pawn': ChessPawn,
  'circle': Circle,
  'circle-dot': CircleDot,
  'clapperboard': Clapperboard,
  'clock': Clock,
  'cloud': Cloud,
  'club': Club,
  'coffee': Coffee,
  'computer': Computer,
  'cooking-pot': CookingPot,
  'cpu': Cpu,
  'croissant': Croissant,
  'cup-soda': CupSoda,
  'dices': Dices,
  'door-open': DoorOpen,
  'dumbbell': Dumbbell,
  'ear': Ear,
  'fence': Fence,
  'file-play': FilePlay,
  'file-text': FileText,
  'film': Film,
  'fish': Fish,
  'flame': Flame,
  'flower': Flower,
  'flower-2': Flower2,
  'footprints': Footprints,
  'frame': Frame,
  'gamepad': Gamepad,
  'gamepad-2': Gamepad2,
  'gem': Gem,
  'gift': Gift,
  'glasses': Glasses,
  'glass-water': GlassWater,
  'graduation-cap': GraduationCap,
  'hammer': Hammer,
  'hand': Hand,
  'handbag': Handbag,
  'headphones': Headphones,
  'heart': Heart,
  'home': Home,
  'house-plus': HousePlus,
  'ice-cream': IceCream,
  'landmark': Landmark,
  'languages': Languages,
  'map': Map,
  'map-pinned': MapPinned,
  'message-circle': MessageCircle,
  'message-circle-more': MessageCircleMore,
  'mic': Mic,
  'mic-2': Mic2,
  'mountain': Mountain,
  'music': Music,
  'origami': Origami,
  'palette': Palette,
  'party-popper': PartyPopper,
  'pencil': Pencil,
  'person-standing': PersonStanding,
  'plane': Plane,
  'puzzle': Puzzle,
  'salad': Salad,
  'sandwich': Sandwich,
  'scissors': Scissors,
  'shelving-unit': ShelvingUnit,
  'shirt': Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'smile': Smile,
  'smartphone': Smartphone,
  'snowflake': Snowflake,
  'soup': Soup,
  'sparkles': Sparkles,
  'star': Star,
  'store': Store,
  'sun': Sun,
  'swords': Swords,
  'table': Table,
  'target': Target,
  'tent': Tent,
  'ticket': Ticket,
  'traffic-cone': TrafficCone,
  'train': Train,
  'tree-pine': TreePine,
  'trophy': Trophy,
  'tv': Tv,
  'type': Type,
  'university': University,
  'user-round': UserRound,
  'users': Users,
  'utensils': Utensils,
  'waves': Waves,
  'wand-sparkles': WandSparkles,
  'wine': Wine,
  'zap': Zap
}

const iconComponent = computed(() => {
  return iconMap[props.iconName] || Sparkles
})
</script>

<template>
  <component
    :is="iconComponent"
    :size="size"
    :class="customClass"
  />
</template>