<script setup lang="ts">
import { computed } from 'vue'
import {
  Amphora,
  Bath,
  Bed,
  BedDouble,
  Bike,
  Bird,
  BookA,
  BookType,
  Bookmark,
  BookOpen,
  BowArrow,
  BrickWall,
  Building,
  Cake,
  CakeSlice,
  Calculator,
  Camera,
  Car,
  Cat,
  ChefHat,
  ChessPawn,
  Circle,
  CircleDot,
  CirclePile,
  Clapperboard,
  Club,
  Coffee,
  Computer,
  CookingPot,
  Cpu,
  Croissant,
  CupSoda,
  Dices,
  Dog,
  DoorOpen,
  Dumbbell,
  Ear,
  Eclipse,
  Fence,
  FilePlay,
  FileText,
  Film,
  Fish,
  Flame,
  Flower,
  Flower2,
  Footprints,
  Frame,
  Gamepad,
  Gamepad2,
  Gem,
  GlassWater,
  Hammer,
  Hand,
  HandCoins,
  Handbag,
  Headphones,
  Heart,
  Home,
  HousePlus,
  Landmark,
  Languages,
  LoaderPinwheel,
  MapPinned,
  MessageCircle,
  MessageCircleMore,
  Mic,
  Mountain,
  Music,
  Palette,
  Pencil,
  PersonStanding,
  Plane,
  Puzzle,
  Salad,
  Sandwich,
  Scissors,
  Shapes,
  ShelvingUnit,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shrimp,
  Smile,
  Smartphone,
  Snowflake,
  Soup,
  Sparkles,
  Spool,
  SquareStar,
  Star,
  Store,
  Sun,
  Swords,
  Target,
  Tent,
  Ticket,
  Toolbox,
  ToyBrick,
  TrafficCone,
  TreePine,
  Tv,
  University,
  Users,
  Utensils,
  Volleyball,
  Waves,
  WandSparkles,
  Wine,
  BoomBox
} from 'lucide-vue-next'

interface Props {
  iconName: string
  size?: number
  customClass?: string
}

const props = withDefaults(defineProps<Props>(), {
  size: 24,
  customClass: ''
})

// Map kebab-case icon names to PascalCase components
const iconMap: Record<string, typeof Sparkles> = {
  'amphora': Amphora,
  'bath': Bath,
  'bed': Bed,
  'bed-double': BedDouble,
  'bike': Bike,
  'bird': Bird,
  'book-a': BookA,
  'book-type': BookType,
  'bookmark': Bookmark,
  'book-open': BookOpen,
  'boom-box': BoomBox,
  'bow-arrow': BowArrow,
  'brick-wall': BrickWall,
  'building': Building,
  'cake': Cake,
  'cake-slice': CakeSlice,
  'calculator': Calculator,
  'camera': Camera,
  'car': Car,
  'cat': Cat,
  'chef-hat': ChefHat,
  'chess-pawn': ChessPawn,
  'circle': Circle,
  'circle-dot': CircleDot,
  'circle-pile': CirclePile,
  'clapperboard': Clapperboard,
  'club': Club,
  'coffee': Coffee,
  'computer': Computer,
  'cooking-pot': CookingPot,
  'cpu': Cpu,
  'croissant': Croissant,
  'cup-soda': CupSoda,
  'dices': Dices,
  'dog': Dog,
  'door-open': DoorOpen,
  'dumbbell': Dumbbell,
  'ear': Ear,
  'eclipse': Eclipse,
  'fence': Fence,
  'file-play': FilePlay,
  'file-text': FileText,
  'film': Film,
  'fish': Fish,
  'flame': Flame,
  'flower': Flower,
  'flower-2': Flower2,
  'footprints': Footprints,
  'frame': Frame,
  'gamepad': Gamepad,
  'gamepad-2': Gamepad2,
  'gem': Gem,
  'glass-water': GlassWater,
  'hammer': Hammer,
  'hand': Hand,
  'hand-coins': HandCoins,
  'handbag': Handbag,
  'headphones': Headphones,
  'heart': Heart,
  'home': Home,
  'house-plus': HousePlus,
  'landmark': Landmark,
  'languages': Languages,
  'loader-pinwheel': LoaderPinwheel,
  'map-pinned': MapPinned,
  'message-circle': MessageCircle,
  'message-circle-more': MessageCircleMore,
  'mic': Mic,
  'mountain': Mountain,
  'music': Music,
  'palette': Palette,
  'pencil': Pencil,
  'person-standing': PersonStanding,
  'plane': Plane,
  'puzzle': Puzzle,
  'salad': Salad,
  'sandwich': Sandwich,
  'scissors': Scissors,
  'shapes': Shapes,
  'shelving-unit': ShelvingUnit,
  'shirt': Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'shrimp': Shrimp,
  'smile': Smile,
  'smartphone': Smartphone,
  'snowflake': Snowflake,
  'soup': Soup,
  'sparkles': Sparkles,
  'spool': Spool,
  'square-star': SquareStar,
  'star': Star,
  'store': Store,
  'sun': Sun,
  'swords': Swords,
  'target': Target,
  'tent': Tent,
  'ticket': Ticket,
  'toolbox': Toolbox,
  'toy-brick': ToyBrick,
  'traffic-cone': TrafficCone,
  'tree-pine': TreePine,
  'tv': Tv,
  'university': University,
  'users': Users,
  'utensils': Utensils,
  'volleyball': Volleyball,
  'waves': Waves,
  'wand-sparkles': WandSparkles,
  'wine': Wine
}

const iconComponent = computed(() => {
  return iconMap[props.iconName] || Sparkles
})
</script>

<template>
  <component
    :is="iconComponent"
    :size="size"
    :class="customClass"
  />
</template>